# LoggerProtocol，最小接口契约

"""最小日志接口契约，不依赖 loguru 运行时实体。"""
# kd_tool/logging/protocols.py
from __future__ import annotations
from typing import Protocol, runtime_checkable, abstractmethod


@runtime_checkable
class LoggerProtocol(Protocol):
    """
    WHY: 日志协议。
    WHAT: 供依赖注入，兼容Loguru。
    HOW: 只定义接口，无实现。
    """

    def debug(self, msg: str, *a, **kw): ...
    def info(self, msg: str, *a, **kw): ...
    def warning(self, msg: str, *a, **kw): ...
    def error(self, msg: str, *a, **kw): ...
    def exception(self, msg: str, *a, **kw): ...
    def success(self, msg: str, *a, **kw): ...
    def bind(self, **kw) -> "LoggerProtocol": ...
    @abstractmethod
    def trace(self, msg: str, *a, **kw): ...
    @abstractmethod
    def add(self, sink, **kwargs): ...
